version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: frontend_supplier
    ports:
      - "5174:5174"
    environment:
      - HOST=0.0.0.0
      - PORT=5174
    restart: always